# HTTP Server
server:
  port: 8080

management:
  security:
    enabled: false

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    org.springframework.web: 'INFO'
    com.atsistemas: 'DEBUG'

cygnus:
  sadr:
    name: sadr
    pingUrl: http://${cygnus.sadr.name}/ping

spring:
   rabbitmq:
     host: rabbitmq
     port: 5672
     username: guest
     password: guest
