info:
  component: Turbine
  
# HTTP Server
server:
  port: 8080

turbine:
  stream:
    port: 8989
  aggregator:
    clusterConfig: CYGNUS
  appConfig: deneb
  
management:
  port: -1
  security:
    enabled: false


spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8080/eureka/

logging:
  file: logs/${spring.application.name}.log
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    com.atsistemas: 'DEBUG'